version: "3.8"

networks:
  backend:
    driver: bridge

services:
  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "127.0.0.1:6379:6379"
    command: ["redis-server", "--appendonly", "yes"] # включаем persistence
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - backend

  bleam:
    build:
      context: ./Bleam
      dockerfile: Dockerfile
    image: bleam:latest   # 👈 фикс
    container_name: bleam
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - JAVA_TOOL_OPTIONS=${JAVA_TOOL_OPTIONS}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - JWT_SECRET_USER=${JWT_SECRET_USER}
      - JWT_SECRET_SERVICE=${JWT_SECRET_SERVICE}
      - JWT_EXPIRATION_SERVICE=${JWT_EXPIRATION_SERVICE}
      - JWT_EXPIRATION_USER=${JWT_EXPIRATION_USER}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - FRONTEND_URL=${FRONTEND_URL}
      - TELEGRAM_URL=${TELEGRAM_URL}
      - WHATSAPP_URL=${WHATSAPP_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=${REDIS_DB}
      - SUCCESS_URL=${SUCCESS_URL}
      - ERROR_URL=${ERROR_URL}
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - backend
    depends_on:
      - redis

  whatsapp-bridge:
    build:
      context: ./whatsapp-bridge
      dockerfile: Dockerfile
    image: whatsapp-bridge:latest   # 👈 фикс
    container_name: whatsapp-bridge
    environment:
      - REDIS_URL=${REDIS_URL}
      - PORT=${WHATSAPP_PORT}
      - SERVICE_NAME=${SERVICE_NAME_WHATSAPP}
      - JWT_SERVICE_SECRET=${JWT_SECRET_SERVICE}
      - PLATFORM_SERVICE_URL=${PLATFORM_SERVICE_URL_WHATSAPP}
    ports:
      - "${WHATSAPP_PORT:-3000}:3000"
    volumes:
      - whatsapp_sessions:/usr/src/app/sessions
    depends_on:
      - redis
      - bleam
    restart: unless-stopped
    networks:
      - backend

  telegram-bridge:
    build:
      context: ./telegram-bridge
      dockerfile: Dockerfile
    image: telegram-bridge:latest   # 👈 фикс
    container_name: telegram-bridge
    environment:
      - REDIS_URL=${REDIS_URL}
      - PORT=${TELEGRAM_PORT}
      - SERVICE_NAME=${SERVICE_NAME_TELEGRAM}
      - JWT_SERVICE_SECRET=${JWT_SECRET_SERVICE}
      - PLATFORM_SERVICE_URL=${PLATFORM_SERVICE_URL_TELEGRAM}
      - TG_WEBHOOK_SECRET_SALT=${TG_WEBHOOK_SECRET_SALT}
      - PUBLIC_DOMAIN=${PUBLIC_DOMAIN}
    ports:
      - "${TELEGRAM_PORT:-3001}:3001"
    depends_on:
      - redis
      - bleam
    restart: unless-stopped
    networks:
      - backend

volumes:
  redis_data:
  whatsapp_sessions: